### ISSUE TITLE
invalid log target error

### ISSUE THREAD

**Issue by MarcoForte** [sabarim/itis#2]
When I try to run `python main.py ./configs/eval/pascal_itis`

I get the following error

```
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    tf.app.run(main)
  File "/home/marco/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 28, in main
    init_log(config)
  File "main.py", line 16, in init_log
    log.initialize([filename], [verbosity], [])
  File "/home/marco/ImageMatting/itis-master/core/Log.py", line 76, in initialize
    assert False, "invalid log target %r" % t
AssertionError: invalid log target 'logs/pascal_itis.log
```

**Comment by MarcoForte** [comment]
Creating a folder called `logs` fixed the error
